# Generated by Django 5.1.1 on 2024-09-29 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('cover_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('finance', 'Finance'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('image1_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image2_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image3_url', models.URLField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('create_blog', 'Can create blogs'), ('edit_blog', 'Can edit blogs'), ('read_blog', 'Can read blogs'), ('remove_blog', 'Can delete blogs')],
            },
        ),
    ]
